language: go
services:
  - docker
go:
  - "1.14"
env:
  - "GO15VENDOREXPERIMENT=1"
before_install:
  - sudo apt-get install -y libcap2-bin
  - sudo make deps
script:
  - sudo make multiarch-build test-integration test-coverage
after_success:
  - |
      if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        git config --global user.name "Deployer" && git config --global user.email foo@bar.com
        go get github.com/tcnksm/ghr
        ghr -u mudler -r luet --replace $TRAVIS_TAG release/
      fi
