language: go
services:
  - docker
go:
  - "1.12"
env:
  - "GO15VENDOREXPERIMENT=1"
before_install:
  - make deps
  - curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-diff-linux-amd64 $HOME/bin/container-diff
script:
  - make test
after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
