on: push
name: Build and release on push
jobs:
  release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Login to quay
        run: echo ${{ secrets.DOCKER_TESTING_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_TESTING_USERNAME }} --password-stdin quay.io
      - name: Install deps
        run: |
            sudo apt-get install -y upx && sudo -E env "PATH=$PATH" make deps
            sudo curl -fSL "https://github.com/genuinetools/img/releases/download/v0.5.11/img-linux-amd64" -o "/usr/bin/img"
            sudo chmod a+x "/usr/bin/img"
      - name: Build test
        run: sudo -E env "PATH=$PATH" make multiarch-build-small
      - name: Login to quay with img
        run: echo ${{ secrets.DOCKER_TESTING_PASSWORD }} | sudo img login -u ${{ secrets.DOCKER_TESTING_USERNAME }} --password-stdin quay.io
      - name: Tests with Img backend
        run: |
            sudo -E env "PATH=$PATH" \
                    env "LUET_BACKEND=img" \
                    make test-integration
      - name: Tests
        run: |
              sudo -E \
                    env "PATH=$PATH" \
                    env "TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                    env "UNIT_TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                    env "UNIT_TEST_DOCKER_IMAGE_REPOSITORY=${{ secrets.DOCKER_TESTING_UNIT_TEST_IMAGE }}" \
                    make test-integration test-coverage
      - name: Build
        run: sudo -E env "PATH=$PATH" make multiarch-build-small && sudo chmod -R 777 release/
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
