on: push
name: Build and release on push
jobs:
  release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Login to quay
        run: echo ${{ secrets.DOCKER_TESTING_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_TESTING_USERNAME }} --password-stdin quay.io
      - name: Install deps
        run: sudo apt-get install -y upx
      - name: Tests
        run: |
              sudo -E \
                    env "PATH=$PATH" \
                    env "TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                    env "UNIT_TEST_DOCKER_IMAGE=${{ secrets.DOCKER_TESTING_IMAGE }}" \
                    env "UNIT_TEST_DOCKER_IMAGE_REPOSITORY=${{ secrets.DOCKER_TESTING_UNIT_TEST_IMAGE }}" \
                    make deps multiarch-build-small test-integration test-coverage
      - name: Build
        run: sudo -E env "PATH=$PATH" make multiarch-build-small && sudo chmod -R 777 release/
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
