
on: pull_request
name: Build and Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
    - name: Tests
      run: sudo -E env "PATH=$PATH" make deps multiarch-build test-integration test-coverage
